default: &default                  # defaultの中にadapter~poolまでが入っている
  adapter: postgresql         
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:      #developの中にdatabase~が入っている
  <<: *default
  database: sample_development

test:           #testの中にdatabase~が入っている
  <<: *default
  database: sample_test

production:                #productionの中にdatabase~passwordまでが入っている
  <<: *default
  database: sample_production
  username: sample
  password: <%= ENV['SAMPLE_DATABASE_PASSWORD'] %>

# データベースの接続設定ファイル